# Generated by Django 3.2.5 on 2022-02-17 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0008_alter_itembasket_basket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Basket.basket'),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
