# Generated by Django 3.2.5 on 2022-02-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_auto_20220217_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='order',
            new_name='basket',
        ),
    ]
