# Generated by Django 3.2.5 on 2022-02-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0004_ordershipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
