# Generated by Django 3.2.5 on 2022-02-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0005_shippinginfo_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipping',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
