# Generated by Django 3.2.5 on 2022-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0006_ordershipping_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
