# Generated by Django 3.2.5 on 2022-02-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
