# Generated by Django 3.2.5 on 2022-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0002_basket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
