# Generated by Django 3.2.5 on 2022-02-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Basket', '0003_alter_basket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ItemBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.basket')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
