# Generated by Django 3.2.5 on 2022-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0004_auto_20220212_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembasket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
