# Generated by Django 3.2.5 on 2022-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0005_itembasket_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembasket',
            name='completed',
        ),
        migrations.AddField(
            model_name='basket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
