# Generated by Django 3.2.5 on 2022-02-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0006_auto_20220212_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
