# Generated by Django 3.2.5 on 2022-02-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0007_basket_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembasket',
            name='basket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Basket.basket'),
        ),
    ]
