# Generated by Django 3.2.5 on 2022-02-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0008_alter_itembasket_basket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='order_date',
        ),
    ]
