# Generated by Django 3.2.5 on 2022-02-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0009_remove_basket_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembasket',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
